INSERT INTO movie (MovieID, Title, Duration, Rating, Description, ReleaseYear) VALUES
(1, 'The Shawshank Redemption', 142, 9.3, 'A banker convicted of uxoricide forms a friendship over a quarter century with a hardened convict, while maintaining his innocence and trying to remain hopeful through simple compassion.', 1994),
(2, 'The Godfather', 175, 9.2, 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', 1972),
(3, 'The Dark Knight', 152, 9.0, 'When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness.', 2008),
(4, 'The Godfather Part II', 202, 9.0, 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.', 1974),
(5, '12 Angry Men', 96, 9.0, 'The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.', 1957),
(6, 'Schindler''s List', 195, 9.0, 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.', 1993),
(7, 'The Lord of the Rings: The Return of the King', 201, 9.0, 'Gandalf and Aragorn lead the World of Men against Sauron''s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.', 2003),
(8, 'Pulp Fiction', 154, 8.9, 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 1994),
(9, 'The Lord of the Rings: The Fellowship of the Ring', 178, 8.8, 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.', 2001),
(10, 'The Good, the Bad and the Ugly', 178, 8.8, 'A bounty-hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.', 1966),
(11, 'Forrest Gump', 142, 8.8, 'The history of the United States from the 1950s to the ''70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.', 1994),
(12, 'Fight Club', 139, 8.8, 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.', 1999),
(13, 'The Lord of the Rings: The Two Towers', 179, 8.8, 'While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron''s new ally, Saruman, and his hordes of Isengard.', 2002),
(14, 'Inception', 148, 8.8, 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.', 2010),
(15, 'Star Wars: Episode V - The Empire Strikes Back', 124, 8.7, 'After the Empire overpowers the Rebel Alliance, Luke Skywalker begins training with Jedi Master Yoda, while Darth Vader and bounty hunter Boba Fett pursue his friends across the galaxy.', 1980),
(16, 'The Matrix', 136, 8.7, 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.', 1999),
(17, 'Goodfellas', 145, 8.7, 'The story of Henry Hill and his life in the mafia, covering his relationship with his wife Karen and his mob partners Jimmy Conway and Tommy DeVito.', 1990),
(18, 'One Flew Over the Cuckoo''s Nest', 133, 8.7, 'A newly admitted mental patient helps his docile companions defy the tyrannical head nurse.', 1975),
(19, 'Se7en', 127, 8.6, 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.', 1995),
(20, 'Seven Samurai', 207, 8.6, 'Farmers from a village exploited by bandits hire a veteran samurai for protection, and he gathers six other samurai to join him.', 1954),
(21, 'It''s a Wonderful Life', 130, 8.6, 'An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.', 1946),
(22, 'The Silence of the Lambs', 118, 8.6, 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.', 1991),
(23, 'City of God', 130, 8.6, 'In the slums of Rio, two kids'' paths diverge as one struggles to become a photographer and the other a kingpin.', 2002),
(24, 'Saving Private Ryan', 169, 8.6, 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.', 1998),
(25, 'Interstellar', 169, 8.6, 'When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.', 2014),
(26, 'Life Is Beautiful', 116, 8.6, 'When an open-minded Jewish librarian and his son become victims of the Holocaust, he uses a perfect mixture of will, humor, and imagination to protect his son from the dangers around their camp.', 1997),
(27, 'The Green Mile', 189, 8.6, 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.', 1999),
(28, 'Star Wars: Episode IV - A New Hope', 121, 8.6, 'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee, and two droids to save the galaxy from the Empire''s world-destroying battle station.', 1977),
(29, 'Terminator 2: Judgment Day', 137, 8.6, 'A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her teenage son, John Connor, from a more advanced and powerful cyborg.', 1991),
(30, 'Back to the Future', 116, 8.5, 'Marty McFly, a teenager, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, eccentric scientist Doc Brown.', 1985),
(31, 'Spirited Away', 125, 8.6, 'During her family''s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, spirits, and a witch, where humans are changed into beasts.', 2001),
(32, 'The Pianist', 150, 8.5, 'A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.', 2002),
(33, 'Psycho', 109, 8.5, 'A secretary embezzles money and checks into a remote motel run by a young man under the domination of his mother.', 1960),
(34, 'Parasite', 132, 8.5, 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.', 2019),
(35, 'Leon: The Professional', 110, 8.5, '12-year-old Mathilda is reluctantly taken in by Léon, a professional assassin, after her family is murdered. Léon and Mathilda form an unusual relationship as she becomes his protégée and learns the assassin''s trade.', 1994),
(36, 'The Lion King', 88, 8.5, 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.', 1994),
(37, 'Gladiator', 155, 8.5, 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.', 2000),
(38, 'American History X', 119, 8.5, 'A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.', 1998),
(39, 'The Departed', 151, 8.5, 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.', 2006),
(40, 'The Usual Suspects', 106, 8.5, 'A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.', 1995),
(41, 'The Prestige', 130, 8.5, 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.', 2006),
(42, 'Whiplash', 106, 8.5, 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student''s potential.', 2014),
(43, 'Casablanca', 102, 8.5, 'A cynical American expatriate struggles to decide whether or not he should help his former lover and her fugitive husband escape French Morocco.', 1942),
(44, 'Grave of the Fireflies', 89, 8.5, 'A young boy and his little sister struggle to survive in Japan during World War II.', 1988),
(45, 'Harakiri', 133, 8.6, 'An elder samurai arrives at a feudal lord''s home and requests to commit seppuku, but there is more to his tale than what it seems.', 1962),
(46, 'The Intouchables', 112, 8.5, 'After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.', 2011),
(47, 'Modern Times', 87, 8.5, 'The Tramp struggles to live in modern industrial society with the help of a young homeless woman.', 1936),
(48, 'Once Upon a Time in the West', 165, 8.5, 'A mysterious stranger with a harmonica joins forces with a notorious desperado to protect a beautiful widow from a ruthless assassin working for the railroad.', 1968),
(49, 'Rear Window', 112, 8.5, 'A wheelchair-bound photographer spies on his neighbors from his apartment window and becomes convinced one of them has committed murder.', 1954),
(50, 'Cinema Paradiso', 155, 8.5, 'A filmmaker recalls his childhood when falling in love with the pictures at the cinema of his home village and forms a deep friendship with the cinema''s projectionist.', 1988),
(51, 'Alien', 117, 8.5, 'The crew of a commercial spacecraft encounters a deadly lifeform after investigating a distress call from an unknown planet.', 1979),
(52, 'City Lights', 87, 8.5, 'With the aid of a wealthy older man, a tramp struggles to help a blind flower girl he has fallen in love with.', 1931),
(53, 'Apocalypse Now', 147, 8.5, 'A U.S. Army officer is sent on a mission to assassinate a renegade Special Forces Colonel who sees himself as a god.', 1979),
(54, 'Memento', 113, 8.4, 'A man with short-term memory loss attempts to track down his wife''s murderer.', 2000),
(55, 'Django Unchained', 165, 8.4, 'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.', 2012),
(56, 'Indiana Jones and the Raiders of the Lost Ark', 115, 8.4, 'In 1936, archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before the Nazis can obtain its awesome powers.', 1981),
(57, 'WALL·E', 98, 8.4, 'In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.', 2008),
(58, 'The Lives of Others', 137, 8.4, 'In 1984 East Berlin, an agent of the secret police is conducting surveillance on a writer and his lover, and finds himself becoming increasingly absorbed by their lives.', 2006),
(59, 'Sunset Blvd.', 110, 8.4, 'A screenwriter develops a dangerous relationship with a faded film star determined to make a triumphant return.', 1950),
(60, 'Paths of Glory', 88, 8.4, 'After refusing to attack an enemy position, a general accuses his soldiers of cowardice and their commanding officer must defend them.', 1957),
(61, 'The Shining', 146, 8.4, 'A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings.', 1980),
(62, 'The Great Dictator', 125, 8.4, 'Dictator Adenoid Hynkel tries to expand his empire while a poor Jewish barber tries to avoid persecution from Hynkel''s regime.', 1940),
(63, 'Avengers: Infinity War', 149, 8.4, 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation puts an end to the universe.', 2018),
(64, 'Witness for the Prosecution', 116, 8.4, 'A veteran British barrister must defend his client in a murder trial that holds not only surprise after surprise but also a deadly secret.', 1957),
(65, 'Aliens', 137, 8.4, 'Ellen Ripley is rescued by a deep salvage team after being in hypersleep for 57 years. The moon that the Nostromo visited has been colonized, but contact is lost. This time, colonial marines have impressive firepower, but will that be enough?', 1986),
(66, 'Spider-Man: Into the Spider-Verse', 117, 8.4, 'Teen Miles Morales becomes the Spider-Man of his universe and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.', 2018),
(67, 'American Beauty', 122, 8.4, 'A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter''s best friend.', 1999),
(68, 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', 95, 8.4, 'An insane general triggers a path to nuclear holocaust that a war room full of politicians and generals frantically tries to stop.', 1964),
(69, 'The Dark Knight Rises', 164, 8.4, 'Eight years after the Joker''s reign of anarchy, Batman, with the help of the enigmatic Catwoman, is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane.', 2012),
(70, 'Oldboy', 120, 8.4, 'After being kidnapped and imprisoned for fifteen years, Oh Dae-Su is released, only to find that he must find his captor in five days.', 2003),
(71, 'Inglourious Basterds', 153, 8.3, 'In Nazi-occupied France, a group of Jewish-American soldiers known as "The Basterds" plan to assassinate Nazi leaders while a theater owner seeks revenge for her family''s murder.', 2009),
(72, 'Amadeus', 160, 8.4, 'The life, success, and troubles of Wolfgang Amadeus Mozart, as told by his peer and secret rival Antonio Salieri, now confined to an insane asylum.', 1984),
(73, 'Coco', 105, 8.4, 'Aspiring musician Miguel, confronted with his family''s ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.', 2017),
(74, 'Toy Story', 81, 8.3, 'A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy''s room.', 1995),
(75, 'Joker', 122, 8.4, 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.', 2019),
(76, 'Braveheart', 178, 8.4, 'Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.', 1995),
(77, 'The Boat', 149, 8.4, 'The claustrophobic world of a WWII German U-boat; boredom, filth, and sheer terror.', 1981),
(78, 'Avengers: Endgame', 181, 8.4, 'After the devastating events of Avengers: Infinity War, the universe is in ruins. The Avengers assemble once more in order to reverse Thanos'' actions and restore balance.', 2019),
(79, 'Princess Mononoke', 134, 8.4, 'On a journey to find the cure for a Tatarigami''s curse, Ashitaka finds himself in the middle of a war between the forest gods and Tatara, a mining colony.', 1997),
(80, 'Once Upon a Time in America', 229, 8.3, 'A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan over thirty years later, where he once again must confront the ghosts and regrets of his old life.', 1984),
(81, 'Good Will Hunting', 126, 8.3, 'Will Hunting, a janitor at M.I.T., has a gift for mathematics but needs help from a psychologist to find direction in his life.', 1997),
(82, 'Your Name.', 106, 8.4, 'Two teenagers share a profound, magical connection upon discovering they are swapping bodies. But things become even more complicated when they try to meet in person.', 2016),
(83, '3 Idiots', 170, 8.4, 'Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently.', 2009),
(84, 'Singin'' in the Rain', 103, 8.3, 'A silent film production company and cast make a difficult transition to sound.', 1952),
(85, 'Requiem for a Dream', 102, 8.3, 'The drug-induced utopias of four Coney Island people are shattered when their addictions run deep.', 2000),
(86, 'Toy Story 3', 103, 8.3, 'The toys are mistakenly delivered to a day-care center instead of the attic before Andy leaves for college, and it''s up to Woody to convince the others to return home.', 2010),
(87, 'High and Low', 143, 8.4, 'An executive of a shoe company becomes a victim of extortion when his chauffeur''s son is kidnapped by mistake and held for ransom.', 1963),
(88, 'Capernaum', 126, 8.4, 'While serving a five-year sentence for a violent crime, a 12-year-old boy sues his parents for neglect.', 2018),
(89, 'Star Wars: Episode VI - Return of the Jedi', 131, 8.3, 'After rescuing Han Solo from Jabba the Hutt, the Rebels attempt to destroy the second Death Star, while Luke struggles to bring his father back from the dark side.', 1983),
(90, 'Eternal Sunshine of the Spotless Mind', 108, 8.3, 'When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories.', 2004),
(91, '2001: A Space Odyssey', 149, 8.3, 'After discovering a mysterious artifact buried beneath the lunar surface, mankind sets off on a quest to find its origins with the help of the intelligent computer HAL 9000.', 1968),
(92, 'Reservoir Dogs', 99, 8.3, 'After a simple jewelry heist goes terribly wrong, the surviving criminals begin to suspect that one of them is a police informant.', 1992),
(93, 'Come and See', 142, 8.4, 'After finding an old rifle, a young boy joins the Soviet resistance movement against ruthless German forces and experiences the horrors of World War II.', 1985),
(94, 'The Hunt', 115, 8.3, 'A teacher lives a lonely life, all the while struggling over his sons custody. His life slowly gets better as he finds love and receives good news from his son, but his new luck is about to be brutally shattered by an innocent little lie.', 2012),
(95, 'Citizen Kane', 119, 8.3, 'Following the death of publishing tycoon Charles Foster Kane, reporters scramble to uncover the meaning of his final utterance: "Rosebud."', 1941),
(96, 'M', 99, 8.3, 'When the police in a German city are unable to catch a child-murderer, other criminals join in the manhunt.', 1931),
(97, 'Lawrence of Arabia', 218, 8.3, 'The story of T.E. Lawrence, the English officer who successfully united and led the Arab tribes during World War I to fight the Turks.', 1962),
(98, 'North by Northwest', 136, 8.3, 'A New York City advertising executive goes on the run after being mistaken for a government agent by a group of foreign spies.', 1959),
(99, 'Vertigo', 128, 8.3, 'A former police detective juggles wrestling with his personal demons and becoming obsessed with a hauntingly beautiful woman.', 1958),
(100, 'Ikiru', 143, 8.3, 'A bureaucrat tries to find meaning in his life after he is diagnosed with terminal cancer.', 1952),
(101, 'Amelie', 122, 8.3, 'Amélie is an innocent and naive girl in Paris with her own sense of justice. She decides to help those around her and, along the way, discovers love.', 2001),
(102, 'The Apartment', 125, 8.3, 'A man tries to rise in his company by letting its executives use his apartment for trysts, but complications and a romance of his own ensue.', 1960),
(103, 'A Clockwork Orange', 136, 8.3, 'In the future, a sadistic gang leader is imprisoned and volunteers for a conduct-aversion experiment, but it doesn''t go as planned.', 1971),
(104, 'Double Indemnity', 107, 8.3, 'An insurance representative lets himself be talked into a murder/insurance fraud scheme that arouses an insurance investigator''s suspicions.', 1944),
(105, 'Full Metal Jacket', 116, 8.3, 'A pragmatic U.S. Marine observes the dehumanizing effects of the Vietnam War on his fellow recruits from boot camp to bloody street fighting in Hue.', 1987),
(106, 'Top Gun: Maverick', 130, 8.3, 'After more than 30 years of service as one of the Navy''s top aviators, Maverick pushes the envelope as a courageous test pilot and mentors a new generation of U.S. Navy pilots.', 2022),
(107, 'Scarface', 170, 8.3, 'In 1980 Miami, a determined Cuban immigrant takes over a drug cartel and succumbs to greed.', 1983),
(108, 'Hamilton', 160, 8.4, 'The real life of one of America''s foremost founding fathers and first Secretary of the Treasury, Alexander Hamilton, filmed live on Broadway.', 2020),
(109, 'Incendies', 131, 8.3, 'Twins journey to the Middle East to discover their family history and fulfill their mother''s last wishes.', 2010),
(110, 'To Kill a Mockingbird', 129, 8.3, 'Atticus Finch, a lawyer in the Depression-era South, defends a black man against an undeserved rape charge and his children against prejudice.', 1962),
(111, 'Heat', 170, 8.3, 'A group of high-end professional thieves start to feel the heat from the LAPD when they unknowingly leave a clue at their latest heist.', 1995),
(112, 'The Sting', 129, 8.3, 'Two grifters team up to pull off the ultimate con.', 1973),
(113, 'Up', 96, 8.3, '78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young stowaway.', 2009),
(114, 'A Separation', 123, 8.3, 'A married couple are faced with a difficult decision - to improve the life of their child by moving to another country or to stay in Iran and look after a deteriorating parent who has Alzheimer''s disease.', 2011),
(115, 'Metropolis', 153, 8.3, 'In a futuristic city sharply divided between the working class and the city planners, the son of the city''s mastermind falls in love with a working-class prophet who predicts the coming of a savior to mediate their differences.', 1927),
(116, 'Taxi Driver', 114, 8.2, 'A mentally unstable veteran works as a nighttime taxi driver in New York City, where the perceived decadence and sleaze fuel his urge for violent action.', 1976),
(117, 'L.A. Confidential', 138, 8.2, 'As corruption grows in 1950s Los Angeles, three policemen one strait-laced, one brutal, and one sleazy - investigate a series of murders with their own brand of justice.', 1997),
(118, 'Die Hard', 132, 8.2, 'An NYPD officer tries to save his wife and several others taken hostage by German terrorists during a Christmas party in Los Angeles.', 1988),
(119, 'Snatch', 102, 8.2, 'Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers, and supposedly Jewish jewelers fight to track down a priceless stolen diamond.', 2000),
(120, 'Indiana Jones and the Last Crusade', 127, 8.2, 'In 1938, after his father goes missing while pursuing the Holy Grail, Indiana Jones finds himself up against the Nazis again to stop them from obtaining its power.', 1989),
(121, 'Bicycle Thieves', 89, 8.3, 'In post-war Italy, a working-class man''s bicycle essential for his job is stolen, and he and his son set out to find it.', 1948),
(122, 'Like Stars on Earth', 165, 8.3, 'An eight-year-old boy is thought to be a troublemaker until the new art teacher discovers the real reason behind his struggles in school.', 2007),
(123, '1917', 119, 8.2, 'Two young British soldiers during the First World War are given an impossible mission: deliver a message deep in enemy territory to stop their own men from walking into a trap.', 2019),
(124, 'Downfall', 156, 8.2, 'Traudl Junge, the final secretary for Adolf Hitler, tells of the Nazi dictator''s final days in his Berlin bunker at the end of WWII.', 2004),
(125, 'Dangal', 161, 8.3, 'Former wrestler Mahavir Singh Phogat trains his daughters Geeta and Babita to become world-class wrestlers against all odds.', 2016),
(126, 'For a Few Dollars More', 132, 8.2, 'Two bounty hunters with the same intentions team up to track down an escaped Mexican outlaw.', 1965),
(127, 'Batman Begins', 140, 8.2, 'After training with his mentor, Batman begins his fight to free crime-ridden Gotham City from corruption.', 2005),
(128, 'The Kid', 68, 8.3, 'The Tramp cares for an abandoned child, but events put that relationship in jeopardy.', 1921),
(129, 'Some Like It Hot', 121, 8.2, 'When two male musicians witness a mob hit, they flee the state in an all-female band disguised as women, but further complications set in.', 1959),
(130, 'The Father', 97, 8.2, 'A man refuses all assistance from his daughter as he ages. As he tries to make sense of his changing circumstances, he begins to doubt his loved ones, his own mind, and the fabric of reality.', 2020),
(131, 'All About Eve', 138, 8.2, 'A seemingly timid but secretly ruthless ingénue insinuates herself into the lives of an aging Broadway star and her circle of theater friends.', 1950),
(132, 'The Wolf of Wall Street', 180, 8.2, 'Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption, and the federal government.', 2013),
(133, 'Green Book', 130, 8.2, 'A working-class Italian-American bouncer becomes the driver of an African-American classical pianist on a tour of venues through the 1960s American South.', 2018),
(134, 'Judgment at Nuremberg', 179, 8.3, 'In 1948, an American court in occupied Germany tries four Nazis accused of war crimes.', 1961),
(135, 'Casino', 178, 8.2, 'A tale of greed, deception, money, power, and murder between two best friends: a mafia enforcer and a casino executive compete for a gambling empire  and for a fast-living socialite.', 1995),
(136, 'Ran', 162, 8.2, 'In Medieval Japan, an elderly warlord retires, handing over his empire to his three sons. However, betrayal, greed, and war soon follow.', 1985),
(137, 'Pan''s Labyrinth', 118, 8.2, 'In the Falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie but captivating fantasy world.', 2006),
(138, 'The Truman Show', 103, 8.2, 'An insurance salesman discovers his whole life is actually a reality TV show.', 1998),
(139, 'There Will Be Blood', 158, 8.2, 'A story of family, religion, hatred, oil, and madness, focusing on a turn-of-the-century prospector in the early days of the oil business.', 2007),
(140, 'Unforgiven', 130, 8.2, 'Retired Old West gunslinger William Munny reluctantly takes on one last job, with the help of his old partner and a young man.', 1992),
(141, 'The Sixth Sense', 107, 8.2, 'A frightened, withdrawn Philadelphia boy who communicates with spirits seeks the help of a disheartened child psychologist.', 1999),
(142, 'Shutter Island', 138, 8.2, 'In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.', 2010),
(143, 'A Beautiful Mind', 135, 8.2, 'After John Nash, a brilliant but asocial mathematician, accepts secret work in cryptography, his life takes a turn for the nightmarish.', 2001),
(144, 'Jurassic Park', 127, 8.2, 'A pragmatic paleontologist visiting an almost complete theme park is tasked with protecting a couple of kids after a power failure causes the park''s cloned dinosaurs to run loose.', 1993),
(145, 'Yojimbo', 110, 8.2, 'A crafty ronin comes to a town divided by two criminal gangs and decides to play them against each other to free the town.', 1961),
(146, 'The Treasure of the Sierra Madre', 126, 8.2, 'Two down-on-their-luck Americans search for gold in Mexico, but greed turns their fortune into tragedy.', 1948),
(147, 'Monty Python and the Holy Grail', 91, 8.2, 'King Arthur and his Knights of the Round Table embark on a surreal, low-budget search for the Holy Grail, encountering many very silly obstacles.', 1975),
(148, 'The Great Escape', 172, 8.2, 'Allied prisoners of war plan for several hundred of their number to escape from a German camp during World War II.', 1963),
(149, 'No Country for Old Men', 122, 8.2, 'Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.', 2007),
(150, 'Spider-Man: No Way Home', 148, 8.2, 'With Spider-Man''s identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds begin to appear.', 2021),
(151, 'Kill Bill: Vol. 1', 111, 8.2, ' After awakening from a four-year coma, a former assassin wreaks vengeance on the team of assassins who betrayed her.', 2003),
(152, 'Rashomon', 88, 8.2, 'A heinous crime and its aftermath are recalled from differing points of view.', 1950),
(153, 'The Thing', 109, 8.2, 'A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.', 1982),
(154, 'Finding Nemo', 100, 8.2, 'After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.', 2003),
(155, 'The Elephant Man', 124, 8.2, 'A Victorian surgeon rescues a heavily disfigured man who is mistreated while scraping a living as a side-show freak.', 1980),
(156, 'Chinatown', 130, 8.2, 'A private detective hired to expose an adulterer finds himself caught up in a web of deceit, corruption, and murder.', 1974),
(157, 'Raging Bull', 129, 8.2, 'The life of boxer Jake LaMotta, whose violence and temper that led him to the top in the ring destroyed his life outside it.', 1980),
(158, 'V for Vendetta', 132, 8.2, 'In a future British tyranny, a shadowy freedom fighter known only by the alias of "V" plots to overthrow the corrupt government with the help of a young woman.', 2005),
(159, 'Gone with the Wind', 238, 8.2, 'A manipulative woman and a roguish man carry on a turbulent love affair in the American South during the Civil War and Reconstruction.', 1939),
(160, 'Lock, Stock and Two Smoking Barrels', 107, 8.2, 'A botched card game in London triggers four friends, thugs, weed-growers, and loan sharks to collide with each other in a series of unexpected events.', 1998),
(161, 'Inside Out', 95, 8.2, 'After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions Joy, Fear, Anger, Disgust, and Sadness conflict on how best to navigate a new city, house, and school.', 2015),
(162, 'Dial M for Murder', 105, 8.2, 'A former tennis player tries to arrange his wife''s murder after learning of her affair.', 1954),
(163, 'The Secret in Their Eyes', 129, 8.2, 'A retired legal counselor writes a novel, hoping to find closure for one of his past unresolved homicide cases and for his unreciprocated love with his superior.', 2009),
(164, 'Howl''s Moving Castle', 119, 8.2, 'When an unconfident young woman is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent yet insecure young wizard and his companions in his legged, walking castle.', 2004),
(165, 'Three Billboards Outside Ebbing, Missouri', 115, 8.1, 'A mother personally challenges the local authorities to solve her daughter''s murder when they fail to catch the culprit.', 2017),
(166, 'The Bridge on the River Kwai', 161, 8.2, 'British POWs are forced to build a railway bridge across the river Kwai for their Japanese captors, unaware of an Allied mission to destroy it.', 1957),
(167, 'Trainspotting', 93, 8.1, 'Renton, deeply immersed in the Edinburgh drug scene, tries to clean up and get out, despite the allure of the drugs and influence of friends.', 1996),
(168, 'Prisoners', 153, 8.1, 'When Keller Dover''s daughter and her friend go missing, he takes matters into his own hands as the police pursue multiple leads and the pressure mounts.', 2013),
(169, 'Warrior', 140, 8.2, 'The youngest son of an alcoholic former boxer returns home, where he''s trained by his father for competition in a mixed martial arts tournament a path that puts him on a collision course with his estranged older brother.', 2011),
(170, 'Fargo', 98, 8.1, 'Jerry Lundegaard''s inept crime falls apart due to his and his henchmen''s bungling and the persistent police work of pregnant Marge Gunderson.', 1996),
(171, 'Gran Torino', 116, 8.1, 'Disgruntled Korean War veteran Walt Kowalski sets out to reform his neighbor, a Hmong teenager who tried to steal Kowalski''s prized possession: his 1972 Gran Torino.', 2008),
(172, 'My Neighbor Totoro', 86, 8.1, 'When two girls move to the country to be near their ailing mother, they have adventures with the wondrous forest spirits who live nearby.', 1988),
(173, 'Catch Me If You Can', 141, 8.1, 'Barely 21 yet, Frank is a skilled forger who has passed as a doctor, lawyer, and pilot. FBI agent Carl becomes obsessed with tracking him down.', 2002),
(174, 'Million Dollar Baby', 132, 8.1, 'A determined woman works with a hardened boxing trainer to become a professional.', 2004),
(175, 'Children of Heaven', 89, 8.2, 'After a boy loses his sister''s pair of shoes, he goes on a series of adventures to find them. When he can''t, he decides to enter a footrace to win a new pair.', 1997),
(176, 'Blade Runner', 117, 8.1, 'A blade runner must pursue and terminate four replicants who stole a ship in space and have returned to Earth to find their creator.', 1982),
(177, 'The Gold Rush', 95, 8.1, 'The Tramp goes the Klondike in search of gold and finds it and more.', 1925),
(178, 'Before Sunrise', 101, 8.1, 'A young man and woman meet on a train in Europe and wind up spending one evening together in Vienna. Unfortunately, both know that this will probably be their only night together.', 1995),
(179, '12 Years a Slave', 134, 8.1, 'In the antebellum United States, Solomon Northup, a free black man from upstate New York, is abducted and sold into slavery.', 2013),
(180, 'Klaus', 96, 8.2, 'A selfish postman and a reclusive toymaker form an unlikely friendship, delivering joy to a cold, dark town that desperately needs it.', 2019),
(181, 'Harry Potter and the Deathly Hallows: Part 2', 130, 8.1, 'Harry, Ron, and Hermione search for Voldemort''s remaining Horcruxes in their effort to destroy the Dark Lord as the final battle rages at Hogwarts.', 2011),
(182, 'On the Waterfront', 108, 8.1, 'An ex-prize fighter turned longshoreman struggles to stand up to his corrupt union bosses.', 1954),
(183, 'Ben-Hur', 212, 8.1, 'After a Jewish prince is betrayed and sent into slavery by a Roman friend, he regains his freedom and comes back for revenge.', 1959),
(184, 'Gone Girl', 149, 8.1, 'With his wife''s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it''s suspected that he may not be innocent.', 2014),
(185, 'The Grand Budapest Hotel', 99, 8.1, 'A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel''s glorious days under an exceptional concierge.', 2014),
(186, 'Wild Strawberries', 91, 8.1, 'After living a life marked by coldness, an aging professor is forced to confront the emptiness of his existence.', 1957),
(187, 'The General', 67, 8.1, 'After being rejected from the Confederate army and labeled a coward, a railroad engineer must single-handedly save his kidnapped fiancée and thwart Union spies.', 1926),
(188, 'The Third Man', 93, 8.1, 'Pulp novelist Holly Martins travels to shadowy, postwar Vienna, only to find himself investigating the mysterious death of an old friend.', 1949),
(189, 'In the Name of the Father', 133, 8.1, 'A man''s coerced confession to an IRA bombing he didn''t commit results in his imprisonment, and that of his father, as well. He works to prove his innocence and uncover the truth.', 1993),
(190, 'The Deer Hunter', 183, 8.1, 'An in-depth examination of the ways in which the Vietnam War impacts and disrupts the lives of people in a small industrial town in Pennsylvania.', 1978),
(191, 'Barry Lyndon', 185, 8.1, 'An Irish rogue wins the heart of a rich widow and assumes her dead husband''s aristocratic position in 18th-century England.', 1975),
(192, 'Hacksaw Ridge', 139, 8.1, 'WWII American Army Medic Desmond T. Doss, who served during the Battle of Okinawa, refuses to kill people and becomes the first man in American history to receive the Medal of Honor without firing a shot.', 2016),
(193, 'The Wages of Fear', 131, 8.2, 'In a decrepit South American village, four men are hired to transport an urgent nitroglycerine shipment without the equipment that would make it safe.', 1953),
(194, 'Memories of Murder', 132, 8.1, 'In a small Korean province in 1986, two detectives struggle with the case of multiple young women being found raped and murdered by an unknown culprit.', 2003),
(195, 'Sherlock Jr.', 45, 8.2, 'A film projectionist longs to be a detective and puts his meager skills to work when he is framed by a rival for stealing his girlfriend''s father''s pocketwatch.', 1924),
(196, 'Wild Tales', 122, 8.1, 'Six short stories that explore the extremities of human behavior involving people in distress.', 2014),
(197, 'Mr. Smith Goes to Washington', 129, 8.1, 'A naive youth leader is appointed to the United States Senate, where he fights for the common man.', 1939),
(198, 'Mad Max: Fury Road', 120, 8.1, 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland, with the aid of female prisoners, a psychotic worshipper, and a drifter named Max.', 2015),
(199, 'The Seventh Seal', 96, 8.1, 'A man seeks answers about life, death, and the existence of God as he plays chess against the Grim Reaper during the Black Plague.', 1957),
(200, 'Mary and Max', 92, 8.1, 'A tale of friendship between two unlikely pen pals: Mary, a lonely, eight-year-old girl living in the suburbs of Melbourne, and Max, a forty-four-year-old, severely obese man living in New York.', 2009),
(201, 'How to Train Your Dragon', 98, 8.1, 'A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself, and learns there may be more to the creatures than he assumed.', 2010),
(202, 'Room', 118, 8.1, 'Held captive for 7 years in an enclosed space, a woman and her young son finally gain their freedom, allowing the boy to experience the outside world for the first time.', 2015),
(203, 'Monsters, Inc.', 92, 8.1, 'In order to power the city, monsters have to scare children, but if they are touched by a child, they are contaminated. Things go awry when one child accidentally enters the monster world.', 2001),
(204, 'Jaws', 124, 8.1, 'When a killer shark unleashes chaos on a beach community, it''s up to a local sheriff, a marine biologist, and an old seafarer to hunt the beast down.', 1975),
(205, 'Dead Poets Society', 128, 8.1, 'English teacher John Keating inspires his students to look at poetry with a different perspective of authentic knowledge and feelings.', 1989),
(206, 'The Big Lebowski', 117, 8.1, 'Jeff "The Dude" Lebowski, mistaken for a millionaire of the same name, seeks restitution for his ruined rug and enlists his bowling buddies for help.', 1998),
(207, 'Tokyo Story', 136, 8.2, 'An aging couple visits their children in Tokyo, only to find that their children are too busy to spend time with them.', 1953),
(208, 'The Passion of Joan of Arc', 114, 8.2, 'In 1431, Jeanne d''Arc is placed on trial on charges of heresy. Her ecclesiastical jurists attempt to force Jeanne to recant her claims of holy visions.', 1928),
(209, 'Hotel Rwanda', 121, 8.1, 'Paul Rusesabagina, a hotel manager, houses over a thousand Tutsi refugees during their struggle against the Hutu militia in Rwanda.', 2004),
(210, 'Ford v Ferrari', 152, 8.1, 'American car designer Carroll Shelby and driver Ken Miles battle corporate interference and the laws of physics to build a revolutionary race car for Ford to defeat Ferrari at Le Mans in 1966.', 2019),
(211, 'Rocky', 120, 8.1, 'A small-time Philadelphia boxer gets a once-in-a-lifetime shot to fight the heavyweight champion in a bout in which he strives to go the distance for his self-respect.', 1976),
(212, 'Platoon', 120, 8.1, 'A young soldier in Vietnam faces a moral crisis when confronted with the horrors of war and the duality of man.', 1986),
(213, 'Ratatouille', 111, 8.1, 'A rat who can cook makes an unusual alliance with a young kitchen worker at a famous Paris restaurant.', 2007),
(214, 'Spotlight', 129, 8.1, 'The true story of how the Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese.', 2015),
(215, 'The Terminator', 107, 8.1, 'A cyborg is sent from the future on a deadly mission. He has to kill Sarah Connor, a young woman whose life will have a great significance in years to come.', 1984),
(216, 'Logan', 137, 8.1, 'In a future where mutants are nearly extinct, an aging and weary Logan leads a quiet life. But when a young mutant arrives, he must protect her from dark forces.', 2017),
(217, 'Stand by Me', 89, 8.1, 'After the death of a friend, a writer recounts a boyhood journey to find the body of a missing boy.', 1986),
(218, 'Rush', 123, 8.1, 'The merciless 1970s rivalry between Formula One rivals James Hunt and Niki Lauda.', 2013),
(219, 'Network', 121, 8.1, 'A television network cynically exploits a deranged former anchor''s ravings and revelations about the news media for its own profit.', 1976),
(220, 'Into the Wild', 148, 8.1, 'After graduating from Emory University, top student and athlete Christopher McCandless abandons his possessions, gives his entire savings to charity, and hitchhikes to Alaska to live in the wilderness.', 2007),
(221, 'Before Sunset', 80, 8.1, 'Nine years after Jesse and Céline first met, they encounter each other again on the French leg of Jesse''s book tour.', 2004),
(222, 'The Wizard of Oz', 102, 8.1, 'Young Dorothy Gale and her dog are swept away by a tornado from their Kansas farm to the magical land of Oz, where they embark on a quest to meet the Wizard.', 1939),
(223, 'Pather Panchali', 125, 8.3, 'Impoverished priest Harihar Ray lives with his wife and children in a small Indian village. When he leaves to seek a better job, his family must endure many hardships.', 1955),
(224, 'Groundhog Day', 101, 8.1, 'A narcissistic TV weatherman finds himself reliving the same day over and over again.', 1993),
(225, 'The Best Years of Our Lives', 170, 8.1, 'Three World War II veterans return home to small-town America to discover that they and their families have been irreparably changed.', 1946),
(226, 'The Exorcist', 122, 8.1, 'When a 12-year-old girl is possessed by a mysterious entity, her mother seeks the help of two priests to save her.', 1973),
(227, 'The Incredibles', 115, 8.0, 'A family of undercover superheroes, trying to live a quiet suburban life, are forced into action to save the world.', 2004),
(228, 'To Be or Not to Be', 99, 8.2, 'During World War II, the Polish theater company uses their abilities to fool the Nazis when their leader is arrested.', 1942),
(229, 'La haine', 98, 8.1, 'Twenty-four hours in the lives of three young men in the French suburbs the day after a violent riot.', 1995),
(230, 'The Battle of Algiers', 121, 8.1, 'In the 1950s, fear and violence escalate as the people of Algiers fight for independence from the French government.', 1966),
(231, 'Pirates of the Caribbean: The Curse of the Black Pearl', 143, 8.1, 'Blacksmith Will Turner teams up with eccentric pirate "Captain" Jack Sparrow to save his love from undead pirates.', 2003),
(232, 'Hachi: A Dog''s Tale', 93, 8.1, 'A college professor bonds with an abandoned dog he takes into his home.', 2009),
(233, 'The Grapes of Wrath', 129, 8.1, 'A poor Midwest family is forced off their land during the Great Depression and heads to California in search of work and a better life.', 1940),
(234, 'Jai Bhim', 164, 8.8, 'A tribal man''s wife turns to a human-rights lawyer to help find her husband who is arrested by the police.', 2021),
(235, 'My Father and My Son', 112, 8.2, 'A widowed journalist returns to his hometown with his son to make peace with his estranged family.', 2005),
(236, 'Amores Perros', 154, 8.1, 'A horrific car accident connects three stories, each involving characters dealing with loss, regret, and life''s harsh realities.', 2000),
(237, 'Rebecca', 130, 8.1, 'A young newlywed arrives at her husbands imposing family estate on a windswept English coast and finds herself battling the shadow of his first wife, Rebecca.', 1940),
(238, 'Cool Hand Luke', 127, 8.1, 'A laid-back Southern man is sentenced to two years in a rural prison, but refuses to conform.', 1967),
(239, 'The Handmaiden', 145, 8.1, 'A con man hires a pickpocket to become the maid of a wealthy heiress to help him seduce her and steal her fortune.', 2016),
(240, 'The 400 Blows', 99, 8.1, 'A young boy, left without attention, delves into a life of petty crime.', 1959),
(241, 'The Sound of Music', 172, 8.1, 'A woman leaves an Austrian convent to become a governess to the children of a Naval officer widower.', 1965),
(242, 'It Happened One Night', 105, 8.1, 'A spoiled heiress running away from her family is helped by a man who is actually a reporter in need of a story.', 1934),
(243, 'Persona', 83, 8.1, 'A nurse is put in charge of an actress who can''t talk and finds that their personas are melding together.', 1966),
(244, 'Life of Brian', 94, 8.0, 'Born on the original Christmas in the stable next door to Jesus, Brian of Nazareth spends his life being mistaken for a messiah.', 1979),
(245, 'The Iron Giant', 86, 8.1, 'A young boy befriends a giant robot from outer space that a paranoid government agent wants to destroy.', 1999),
(246, 'The Help', 146, 8.1, 'An aspiring author during the civil rights movement of the 1960s decides to write a book detailing the African-American maids'' point of view on the white families for which they work.', 2011),
(247, 'Dersu Uzala', 142, 8.2, 'The story of a Russian soldier and explorer who meets a Goldi man in the forests of Siberia and the friendship that develops between them.', 1975),
(248, 'Aladdin', 90, 8.0, 'A kind-hearted street urchin and a power-hungry Grand Vizier vie for a magic lamp that has the power to make their deepest wishes come true.', 1992),
(249, 'Gandhi', 191, 8.0, 'The life of Mahatma Gandhi, the lawyer who became the leader of the non-violent independence movement against the British rule of India.', 1982),
(250, 'Dances with Wolves', 181, 8.0, 'Lieutenant John Dunbar, assigned to a remote western Civil War outpost, befriends wolves and Native Americans, making him an intolerable aberration in the military.', 1990);
